# Generated by Django 5.2 on 2025-04-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_photo_delete_itemphoto_alter_item_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='photos',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AddField(
            model_name='item',
            name='photos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
