# Generated by Django 5.2 on 2025-04-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='item',
            name='phone_numbers',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RemoveField(
            model_name='item',
            name='photos',
        ),
        migrations.AlterField(
            model_name='item',
            name='working_hours',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='item',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='items', to='services.itemphoto'),
        ),
    ]
