# Generated by Django 5.2 on 2025-04-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='instagram',
            field=models.TextField(blank=True),
        ),
    ]
